# Generated by Django 2.0 on 2020-08-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotacharacters',
            name='hero_type',
            field=models.CharField(choices=[('S', 'Strength'), ('A', 'Agility'), ('I', 'Intelligence')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
